name: CI

on: 
  - push

jobs:
  container:
    name: Build derivation
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags') # Run only branches (tags and main will build and publish)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-stable
      - run: nix-build
  container_publish:
    name: Build and publish docker container
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/container' || startsWith(github.ref, 'refs/tags') # Run only on main or tags
    env:
      DOCKER_NAME: ghcr.io/${GITHUB_REPOSITORY}/discord-bot
      DOCKER_TAG: github.ref == 'refs/heads/main' && 'latest' || github.ref == 'refs/heads/container' && 'testing' || 'tag'
    steps:
      - name: Set DOCKER_TAG for tag
        if: startsWith(github.ref, 'refs/tags')
        run:
          echo "TAG=$(echo "${{ github.ref }}" | sed 's/^refs\/tags\/v//g')" >> "$GITHUB_ENV"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u ${GITHUB_ACTOR} -p "${{ secrets.GITHUB_TOKEN }}"
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-stable
      - run: nix-build --arg dockerName "'$DOCKER_NAME'" --arg dockerTag "'$DOCKER_TAG'" -A docker
      - name: Build and publish docker image
        run: |
          docker load < result
          docker push "$DOCKER_NAME":"$DOCKER_TAG"
